code-critics
ruleLongMethodsRuleV1FalsePositive

	^ #(#(#(#RGMethodDefinition #(#TonelSourceScannerTest #testScanForComment #false)) #'2021-12-10T01:57:31.035763+01:00') #(#(#RGMethodDefinition #(#TonelSourceScannerTest #testScanForString #false)) #'2021-12-10T02:02:12.675741+01:00') #(#(#RGMethodDefinition #(#TonelSourceScannerTest #testScanForLiteralArray #false)) #'2021-12-10T02:02:26.31286+01:00') )