code-critics
ruleUtilityMethodsRuleV1FalsePositive

	^ #(#(#(#RGMethodDefinition #(#TonelReaderTest #newMemoryFileSystemSnapshot:writtenBy: #false)) #'2021-12-10T01:08:27.87779+01:00') #(#(#RGMethodDefinition #(#TonelParserTest #parse:rule: #false)) #'2021-12-10T01:29:26.807913+01:00') #(#(#RGMethodDefinition #(#TonelReaderTest #withTonelWriterClassesDo: #false)) #'2021-12-10T01:35:12.381675+01:00') #(#(#RGMethodDefinition #(#TonelReaderTraitCompositionTest #readDefinitionOfClass:fromPackage:whitContent: #false)) #'2021-12-10T01:58:46.902012+01:00') )