code-critics
ruleInconsistentMethodClassificationRuleV1FalsePositive

	^ #(#(#(#RGMethodDefinition #(#TonelRepository #readStreamForFileNamed:do: #false)) #'2021-12-10T01:54:43.051353+01:00') #(#(#RGMethodDefinition #(#TonelRepository #loadAllFileNames #false)) #'2021-12-10T01:56:02.206195+01:00') #(#(#RGMethodDefinition #(#TonelRepository #versionWithInfo:ifAbsent: #false)) #'2021-12-10T02:01:55.236877+01:00') )